#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Run a 20-step Qwen3-ASR smoke finetune inside the speech Docker image.

Required environment variables:
  MODEL_PATH      Absolute host path to a Qwen3-ASR model directory.
  DATASET_DIR     Absolute host path to a dataset dir containing dataset_info.json.
  DATASET_NAME    Training dataset name defined in dataset_info.json.
  EVAL_DATASET    Validation dataset name defined in dataset_info.json.
  OUTPUT_DIR      Absolute host path for smoke outputs.

Optional environment variables:
  IMAGE           Docker image tag. Default: llamafactory:speech-fa2
  GPU_ID          Physical GPU id to expose. Default: 0
  HF_CACHE        Absolute host path to Hugging Face cache to mount at /smoke/hf
  MAX_STEPS       Default: 20
  MAX_SAMPLES     Default: 64
  RUN_NAME        Default: qwen3_asr_docker_smoke
  MOUNT_MNT       auto|0|1. Default: auto
  OFFLINE         0|1. Default: 0
  DRY_RUN         0|1. Default: 0

Example:
  IMAGE=llamafactory:speech-fa2-20260309 \
  GPU_ID=6 \
  HF_CACHE=/data2/mayufeng/docker_smoke/hf \
  MODEL_PATH=/data2/mayufeng/models/Qwen3-ASR-0.6B \
  DATASET_DIR=/data2/mayufeng/docker_smoke/hausa100_qwen3_asr \
  DATASET_NAME=qwen3_asr_hausa100_train \
  EVAL_DATASET=qwen3_asr_hausa100_valid \
  OUTPUT_DIR=/data3/mayufeng/docker_smoke_output/qwen3_asr_smoke20 \
  MOUNT_MNT=1 \
  scripts/docker/run_qwen3_asr_smoke.sh
EOF
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

die() {
  echo "[error] $*" >&2
  exit 1
}

require_abs_dir() {
  local value="$1"
  local name="$2"
  [[ -n "$value" ]] || die "Set ${name}."
  [[ "$value" = /* ]] || die "${name} must be an absolute path: ${value}"
  [[ -d "$value" ]] || die "${name} does not exist or is not a directory: ${value}"
}

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/../.." && pwd)"

IMAGE="${IMAGE:-llamafactory:speech-fa2}"
GPU_ID="${GPU_ID:-0}"
MODEL_PATH="${MODEL_PATH:-}"
DATASET_DIR="${DATASET_DIR:-}"
DATASET_NAME="${DATASET_NAME:-}"
EVAL_DATASET="${EVAL_DATASET:-}"
OUTPUT_DIR="${OUTPUT_DIR:-}"
HF_CACHE="${HF_CACHE:-}"
MAX_STEPS="${MAX_STEPS:-20}"
MAX_SAMPLES="${MAX_SAMPLES:-64}"
RUN_NAME="${RUN_NAME:-qwen3_asr_docker_smoke}"
MOUNT_MNT="${MOUNT_MNT:-auto}"
OFFLINE="${OFFLINE:-0}"
DRY_RUN="${DRY_RUN:-0}"

require_abs_dir "$MODEL_PATH" "MODEL_PATH"
require_abs_dir "$DATASET_DIR" "DATASET_DIR"
[[ -f "${DATASET_DIR}/dataset_info.json" ]] || die "DATASET_DIR must contain dataset_info.json: ${DATASET_DIR}"
[[ -n "$DATASET_NAME" ]] || die "Set DATASET_NAME."
[[ -n "$EVAL_DATASET" ]] || die "Set EVAL_DATASET."
[[ -n "$OUTPUT_DIR" ]] || die "Set OUTPUT_DIR."
mkdir -p "$OUTPUT_DIR"
OUTPUT_DIR="$(cd -- "$OUTPUT_DIR" && pwd)"
MODEL_PATH="$(cd -- "$MODEL_PATH" && pwd)"
DATASET_DIR="$(cd -- "$DATASET_DIR" && pwd)"

if [[ -n "$HF_CACHE" ]]; then
  [[ "$HF_CACHE" = /* ]] || die "HF_CACHE must be an absolute path: ${HF_CACHE}"
  mkdir -p "$HF_CACHE"
  HF_CACHE="$(cd -- "$HF_CACHE" && pwd)"
fi

CONFIG_PATH="${OUTPUT_DIR}/qwen3_asr_smoke_20step.yaml"
CONTAINER_CONFIG_PATH="/smoke/output/$(basename "$CONFIG_PATH")"

cat > "$CONFIG_PATH" <<EOF
### Qwen3-ASR smoke finetune (generated by scripts/docker/run_qwen3_asr_smoke.sh)

### model
model_name_or_path: /smoke/model
template: qwen3_asr
trust_remote_code: false

### method
stage: sft
do_train: true
do_eval: true
finetuning_type: lora
flash_attn: fa2
bf16: true

### lora
lora_rank: 8
lora_alpha: 16
lora_dropout: 0.05
lora_target:
  - q_proj
  - k_proj
  - v_proj
  - o_proj
  - gate_proj
  - up_proj
  - down_proj

### dataset
dataset_dir: /smoke/data
dataset: ${DATASET_NAME}
eval_dataset: ${EVAL_DATASET}
max_samples: ${MAX_SAMPLES}
cutoff_len: 4096
preprocessing_num_workers: 4
preprocessing_batch_size: 8
overwrite_cache: true
packing: false
neat_packing: false
dynamic_prompt_packing: false
dynamic_prompt_sampling: false

### audio
audio_sampling_rate: 16000
audio_padding: longest

### output
output_dir: /smoke/output
overwrite_output_dir: true
logging_steps: 5
save_strategy: steps
save_steps: ${MAX_STEPS}
save_total_limit: 1
report_to: none

### eval
eval_strategy: steps
eval_steps: ${MAX_STEPS}
per_device_eval_batch_size: 1
predict_with_generate: true
compute_wer_cer: true
eval_loss_on_full_dataset: false

### generate
do_sample: false
num_beams: 1
max_new_tokens: 128

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
learning_rate: 1.0e-4
max_steps: ${MAX_STEPS}
lr_scheduler_type: cosine
warmup_ratio: 0.02
report_to: none

### perf
dataloader_num_workers: 0
run_name: ${RUN_NAME}
EOF

docker_args=(
  run
  --rm
  --ipc=host
  --gpus "device=${GPU_ID}"
  -w /app
  -e HOME=/tmp/lf-home
  -e XDG_CACHE_HOME=/tmp/lf-xdg
  -e TMPDIR=/tmp/lf-tmp
  -v "${REPO_ROOT}:/app"
  -v "${MODEL_PATH}:/smoke/model:ro"
  -v "${DATASET_DIR}:/smoke/data:ro"
  -v "${OUTPUT_DIR}:/smoke/output"
)

if [[ -n "$HF_CACHE" ]]; then
  docker_args+=(-e HF_HOME=/smoke/hf -v "${HF_CACHE}:/smoke/hf")
fi

if [[ "$OFFLINE" == "1" ]]; then
  docker_args+=(-e HF_HUB_OFFLINE=1 -e TRANSFORMERS_OFFLINE=1)
fi

if [[ "$MOUNT_MNT" == "1" || ( "$MOUNT_MNT" == "auto" && -d /mnt ) ]]; then
  docker_args+=(-v /mnt:/mnt)
fi

cmd=(
  docker
  "${docker_args[@]}"
  "${IMAGE}"
  /opt/conda/bin/llamafactory-cli
  train
  "${CONTAINER_CONFIG_PATH}"
)

{
  printf '%q ' "${cmd[@]}"
  printf '\n'
} > "${OUTPUT_DIR}/training_command.txt"

echo "[info] config: ${CONFIG_PATH}"
echo "[info] output: ${OUTPUT_DIR}"
echo "[info] command: ${OUTPUT_DIR}/training_command.txt"

if [[ "$DRY_RUN" == "1" ]]; then
  cat "${OUTPUT_DIR}/training_command.txt"
  exit 0
fi

"${cmd[@]}"
