# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: endpointing.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'endpointing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x65ndpointing.proto\x12\x0e\x65ndpointing.v1\"\xe8\x01\n\x12\x45ndpointingRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x0c\n\x04lang\x18\x03 \x01(\t\x12 \n\x03\x61sr\x18\x04 \x01(\x0b\x32\x13.endpointing.v1.Asr\x12,\n\x07history\x18\x05 \x03(\x0b\x32\x1b.endpointing.v1.HistoryTurn\x12(\n\x07options\x18\x06 \x01(\x0b\x32\x17.endpointing.v1.Options\x12\"\n\x04meta\x18\x07 \x01(\x0b\x32\x14.endpointing.v1.Meta\"\x13\n\x03\x41sr\x12\x0c\n\x04text\x18\x01 \x01(\t\"?\n\x0bHistoryTurn\x12\"\n\x04role\x18\x01 \x01(\x0e\x32\x14.endpointing.v1.Role\x12\x0c\n\x04text\x18\x02 \x01(\t\"Y\n\x07Options\x12 \n\x18treat_unaddressed_as_eou\x18\x01 \x01(\x08\x12\x1a\n\reou_threshold\x18\x02 \x01(\x01H\x00\x88\x01\x01\x42\x10\n\x0e_eou_threshold\"\x8f\x01\n\x04Meta\x12\x14\n\x0c\x64\x65vice_model\x18\x01 \x01(\t\x12\x13\n\x0b\x61pp_version\x18\x02 \x01(\t\x12.\n\x05\x65xtra\x18\x64 \x03(\x0b\x32\x1f.endpointing.v1.Meta.ExtraEntry\x1a,\n\nExtraEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xaa\x01\n\x13\x45ndpointingResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\r\n\x05label\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x01\x12\r\n\x05model\x18\x04 \x01(\t\x12\x12\n\nlatency_ms\x18\x05 \x01(\x05\x12\r\n\x05p_eou\x18\x06 \x01(\x01\x12\x13\n\x0bp_cont_user\x18\x07 \x01(\x01\x12\x15\n\rp_unaddressed\x18\x08 \x01(\x01*5\n\x04Role\x12\x14\n\x10ROLE_UNSPECIFIED\x10\x00\x12\x08\n\x04USER\x10\x01\x12\r\n\tASSISTANT\x10\x02\x32j\n\x12\x45ndpointingService\x12T\n\x07Predict\x12\".endpointing.v1.EndpointingRequest\x1a#.endpointing.v1.EndpointingResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'endpointing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_META_EXTRAENTRY']._loaded_options = None
  _globals['_META_EXTRAENTRY']._serialized_options = b'8\001'
  _globals['_ROLE']._serialized_start=768
  _globals['_ROLE']._serialized_end=821
  _globals['_ENDPOINTINGREQUEST']._serialized_start=38
  _globals['_ENDPOINTINGREQUEST']._serialized_end=270
  _globals['_ASR']._serialized_start=272
  _globals['_ASR']._serialized_end=291
  _globals['_HISTORYTURN']._serialized_start=293
  _globals['_HISTORYTURN']._serialized_end=356
  _globals['_OPTIONS']._serialized_start=358
  _globals['_OPTIONS']._serialized_end=447
  _globals['_META']._serialized_start=450
  _globals['_META']._serialized_end=593
  _globals['_META_EXTRAENTRY']._serialized_start=549
  _globals['_META_EXTRAENTRY']._serialized_end=593
  _globals['_ENDPOINTINGRESPONSE']._serialized_start=596
  _globals['_ENDPOINTINGRESPONSE']._serialized_end=766
  _globals['_ENDPOINTINGSERVICE']._serialized_start=823
  _globals['_ENDPOINTINGSERVICE']._serialized_end=929
# @@protoc_insertion_point(module_scope)
