# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from . import endpointing_pb2 as endpointing__pb2

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in endpointing_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class EndpointingServiceStub(object):
    """Endpointing (turn-end) classification service."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Predict = channel.unary_unary(
            "/endpointing.v1.EndpointingService/Predict",
            request_serializer=endpointing__pb2.EndpointingRequest.SerializeToString,
            response_deserializer=endpointing__pb2.EndpointingResponse.FromString,
            _registered_method=True,
        )


class EndpointingServiceServicer(object):
    """Endpointing (turn-end) classification service."""

    def Predict(self, request, context):
        """Predict returns one of: "<EOU>" | "<CONT_USER>" | "<UNADDRESSED>"."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_EndpointingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Predict": grpc.unary_unary_rpc_method_handler(
            servicer.Predict,
            request_deserializer=endpointing__pb2.EndpointingRequest.FromString,
            response_serializer=endpointing__pb2.EndpointingResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("endpointing.v1.EndpointingService", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("endpointing.v1.EndpointingService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class EndpointingService(object):
    """Endpointing (turn-end) classification service."""

    @staticmethod
    def Predict(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/endpointing.v1.EndpointingService/Predict",
            endpointing__pb2.EndpointingRequest.SerializeToString,
            endpointing__pb2.EndpointingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
