# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: endpointing.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='endpointing.proto',
  package='endpointing.v1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x65ndpointing.proto\x12\x0e\x65ndpointing.v1\"\xe8\x01\n\x12\x45ndpointingRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x0c\n\x04lang\x18\x03 \x01(\t\x12 \n\x03\x61sr\x18\x04 \x01(\x0b\x32\x13.endpointing.v1.Asr\x12,\n\x07history\x18\x05 \x03(\x0b\x32\x1b.endpointing.v1.HistoryTurn\x12(\n\x07options\x18\x06 \x01(\x0b\x32\x17.endpointing.v1.Options\x12\"\n\x04meta\x18\x07 \x01(\x0b\x32\x14.endpointing.v1.Meta\"\x13\n\x03\x41sr\x12\x0c\n\x04text\x18\x01 \x01(\t\"?\n\x0bHistoryTurn\x12\"\n\x04role\x18\x01 \x01(\x0e\x32\x14.endpointing.v1.Role\x12\x0c\n\x04text\x18\x02 \x01(\t\"Y\n\x07Options\x12 \n\x18treat_unaddressed_as_eou\x18\x01 \x01(\x08\x12\x1a\n\reou_threshold\x18\x02 \x01(\x01H\x00\x88\x01\x01\x42\x10\n\x0e_eou_threshold\"\x8f\x01\n\x04Meta\x12\x14\n\x0c\x64\x65vice_model\x18\x01 \x01(\t\x12\x13\n\x0b\x61pp_version\x18\x02 \x01(\t\x12.\n\x05\x65xtra\x18\x64 \x03(\x0b\x32\x1f.endpointing.v1.Meta.ExtraEntry\x1a,\n\nExtraEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xaa\x01\n\x13\x45ndpointingResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\r\n\x05label\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x01\x12\r\n\x05model\x18\x04 \x01(\t\x12\x12\n\nlatency_ms\x18\x05 \x01(\x05\x12\r\n\x05p_eou\x18\x06 \x01(\x01\x12\x13\n\x0bp_cont_user\x18\x07 \x01(\x01\x12\x15\n\rp_unaddressed\x18\x08 \x01(\x01*5\n\x04Role\x12\x14\n\x10ROLE_UNSPECIFIED\x10\x00\x12\x08\n\x04USER\x10\x01\x12\r\n\tASSISTANT\x10\x02\x32j\n\x12\x45ndpointingService\x12T\n\x07Predict\x12\".endpointing.v1.EndpointingRequest\x1a#.endpointing.v1.EndpointingResponse\"\x00\x62\x06proto3'
)

_ROLE = _descriptor.EnumDescriptor(
  name='Role',
  full_name='endpointing.v1.Role',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ROLE_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='USER', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ASSISTANT', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=439,
  serialized_end=492,
)
_sym_db.RegisterEnumDescriptor(_ROLE)

Role = enum_type_wrapper.EnumTypeWrapper(_ROLE)
ROLE_UNSPECIFIED = 0
USER = 1
ASSISTANT = 2



_ENDPOINTINGREQUEST = _descriptor.Descriptor(
  name='EndpointingRequest',
  full_name='endpointing.v1.EndpointingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_id', full_name='endpointing.v1.EndpointingRequest.request_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='session_id', full_name='endpointing.v1.EndpointingRequest.session_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lang', full_name='endpointing.v1.EndpointingRequest.lang', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='asr', full_name='endpointing.v1.EndpointingRequest.asr', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='history', full_name='endpointing.v1.EndpointingRequest.history', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='options', full_name='endpointing.v1.EndpointingRequest.options', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='meta', full_name='endpointing.v1.EndpointingRequest.meta', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=267,
)


_ASR = _descriptor.Descriptor(
  name='Asr',
  full_name='endpointing.v1.Asr',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='endpointing.v1.Asr.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=269,
  serialized_end=288,
)


_HISTORYTURN = _descriptor.Descriptor(
  name='HistoryTurn',
  full_name='endpointing.v1.HistoryTurn',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='role', full_name='endpointing.v1.HistoryTurn.role', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='text', full_name='endpointing.v1.HistoryTurn.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=290,
  serialized_end=353,
)


_OPTIONS = _descriptor.Descriptor(
  name='Options',
  full_name='endpointing.v1.Options',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='treat_unaddressed_as_eou', full_name='endpointing.v1.Options.treat_unaddressed_as_eou', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='eou_threshold', full_name='endpointing.v1.Options.eou_threshold', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_eou_threshold', full_name='endpointing.v1.Options._eou_threshold',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
      fields=[]),
  ],
  serialized_start=355,
  serialized_end=444,
)


_META_EXTRAENTRY = _descriptor.Descriptor(
  name='ExtraEntry',
  full_name='endpointing.v1.Meta.ExtraEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='endpointing.v1.Meta.ExtraEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='endpointing.v1.Meta.ExtraEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=401,
  serialized_end=445,
)

_META = _descriptor.Descriptor(
  name='Meta',
  full_name='endpointing.v1.Meta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_model', full_name='endpointing.v1.Meta.device_model', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='app_version', full_name='endpointing.v1.Meta.app_version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='extra', full_name='endpointing.v1.Meta.extra', index=2,
      number=100, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_META_EXTRAENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=447,
  serialized_end=590,
)


_ENDPOINTINGRESPONSE = _descriptor.Descriptor(
  name='EndpointingResponse',
  full_name='endpointing.v1.EndpointingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_id', full_name='endpointing.v1.EndpointingResponse.request_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='label', full_name='endpointing.v1.EndpointingResponse.label', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='confidence', full_name='endpointing.v1.EndpointingResponse.confidence', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='model', full_name='endpointing.v1.EndpointingResponse.model', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='latency_ms', full_name='endpointing.v1.EndpointingResponse.latency_ms', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='p_eou', full_name='endpointing.v1.EndpointingResponse.p_eou', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='p_cont_user', full_name='endpointing.v1.EndpointingResponse.p_cont_user', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='p_unaddressed', full_name='endpointing.v1.EndpointingResponse.p_unaddressed', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=593,
  serialized_end=763,
)

_ENDPOINTINGREQUEST.fields_by_name['asr'].message_type = _ASR
_ENDPOINTINGREQUEST.fields_by_name['history'].message_type = _HISTORYTURN
_ENDPOINTINGREQUEST.fields_by_name['options'].message_type = _OPTIONS
_ENDPOINTINGREQUEST.fields_by_name['meta'].message_type = _META
_HISTORYTURN.fields_by_name['role'].enum_type = _ROLE
_OPTIONS.oneofs_by_name['_eou_threshold'].fields.append(
  _OPTIONS.fields_by_name['eou_threshold'])
_OPTIONS.fields_by_name['eou_threshold'].containing_oneof = _OPTIONS.oneofs_by_name['_eou_threshold']
_META_EXTRAENTRY.containing_type = _META
_META.fields_by_name['extra'].message_type = _META_EXTRAENTRY
DESCRIPTOR.message_types_by_name['EndpointingRequest'] = _ENDPOINTINGREQUEST
DESCRIPTOR.message_types_by_name['Asr'] = _ASR
DESCRIPTOR.message_types_by_name['HistoryTurn'] = _HISTORYTURN
DESCRIPTOR.message_types_by_name['Options'] = _OPTIONS
DESCRIPTOR.message_types_by_name['Meta'] = _META
DESCRIPTOR.message_types_by_name['EndpointingResponse'] = _ENDPOINTINGRESPONSE
DESCRIPTOR.enum_types_by_name['Role'] = _ROLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EndpointingRequest = _reflection.GeneratedProtocolMessageType('EndpointingRequest', (_message.Message,), {
  'DESCRIPTOR' : _ENDPOINTINGREQUEST,
  '__module__' : 'endpointing_pb2'
  # @@protoc_insertion_point(class_scope:endpointing.v1.EndpointingRequest)
  })
_sym_db.RegisterMessage(EndpointingRequest)

Asr = _reflection.GeneratedProtocolMessageType('Asr', (_message.Message,), {
  'DESCRIPTOR' : _ASR,
  '__module__' : 'endpointing_pb2'
  # @@protoc_insertion_point(class_scope:endpointing.v1.Asr)
  })
_sym_db.RegisterMessage(Asr)

HistoryTurn = _reflection.GeneratedProtocolMessageType('HistoryTurn', (_message.Message,), {
  'DESCRIPTOR' : _HISTORYTURN,
  '__module__' : 'endpointing_pb2'
  # @@protoc_insertion_point(class_scope:endpointing.v1.HistoryTurn)
  })
_sym_db.RegisterMessage(HistoryTurn)

Options = _reflection.GeneratedProtocolMessageType('Options', (_message.Message,), {
  'DESCRIPTOR' : _OPTIONS,
  '__module__' : 'endpointing_pb2'
  # @@protoc_insertion_point(class_scope:endpointing.v1.Options)
  })
_sym_db.RegisterMessage(Options)

Meta = _reflection.GeneratedProtocolMessageType('Meta', (_message.Message,), {

  'ExtraEntry' : _reflection.GeneratedProtocolMessageType('ExtraEntry', (_message.Message,), {
    'DESCRIPTOR' : _META_EXTRAENTRY,
    '__module__' : 'endpointing_pb2'
    # @@protoc_insertion_point(class_scope:endpointing.v1.Meta.ExtraEntry)
    })
  ,
  'DESCRIPTOR' : _META,
  '__module__' : 'endpointing_pb2'
  # @@protoc_insertion_point(class_scope:endpointing.v1.Meta)
  })
_sym_db.RegisterMessage(Meta)
_sym_db.RegisterMessage(Meta.ExtraEntry)

EndpointingResponse = _reflection.GeneratedProtocolMessageType('EndpointingResponse', (_message.Message,), {
  'DESCRIPTOR' : _ENDPOINTINGRESPONSE,
  '__module__' : 'endpointing_pb2'
  # @@protoc_insertion_point(class_scope:endpointing.v1.EndpointingResponse)
  })
_sym_db.RegisterMessage(EndpointingResponse)


# @@protoc_insertion_point(module_scope)

